version: '3.4'
services:
  gerator:
    image: win/gerator
    container_name: gerator
    depends_on:
      - db
    build: 
      context: .    
    ports:
      - "8083:8083" 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
  db:    
    image: postgres:12
    container_name: postgres
    env_file:
      - .env
    restart: always    
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./data/postgres/script_sql:/docker-entrypoint-initdb.d/
  


