version: '3.4'
services:
  gerator:
    image: win/gerator
    container_name: gerator
    build: 
      context: .    
    ports:
      - "8083:8083" 
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped



